//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwardTransfer
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string BeneficaryBank { get; set; }
        public string BeneficaryName { get; set; }
        public string DestinationAccountNo { get; set; }
        public Nullable<int> BeneficarySwiftCode { get; set; }
        public string BeneficaryAddress { get; set; }
        public string IBAN { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
