//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedback
    {
        public int id { get; set; }
        public string Clientname { get; set; }
        public string email { get; set; }
        public string Message { get; set; }
        public string datesent { get; set; }
    }
}
