//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegister
    {
        public int tblRegID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Othername { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string AccountType { get; set; }
        public string DOB { get; set; }
        public string AccountNo { get; set; }
        public string password { get; set; }
        public string currencyType { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
