//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransfer
    {
        public int transferID { get; set; }
        public string AcctNo { get; set; }
        public string RecipientAcctNo { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public string RoutingNumber { get; set; }
        public string Amount { get; set; }
        public string Status { get; set; }
        public string DateSent { get; set; }
    }
}
