//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCode
    {
        public int Id { get; set; }
        public string AccountNo { get; set; }
        public string COT { get; set; }
        public string TAX { get; set; }
        public string IMF { get; set; }
        public Nullable<System.DateTime> DateGenerated { get; set; }
        public string Status { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
