//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNKMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawRequest
    {
        public int Id { get; set; }
        public string WalletId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string MaintainceFeeStatus { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> MaintainceFee { get; set; }
    
        public virtual CR_Account CR_Account { get; set; }
    }
}
